---
nav:
  - index.md
  - "Migration Guide": "migration_guide.md"
  - "{{ project_name }} with Projen": "projen.md"
  - "{{ project_name }} with Projen and Taskfile": "projen_with_taskfile.md"
  - "Prerequisites": "prerequisites.md"
