#!/bin/bash

set -e

rm -rf build dist
npm install fs-extra
./scripts/generate-markdown
cd build/docs
if [ ! -d .venv ]; then
  python3 -m venv --system-site-packages .venv
fi
source .venv/bin/activate
python3 -m pip install \
    mkdocs~=1.6.0 \
    pygments>=2.12 \
    mkdocs-awesome-pages-plugin~=2.9.2 \
    mkdocs-material~=9.5.21 \
    mkdocs-redirects~=1.2.0 \
    mkdocs-typedoc~=1.0.2 \
    mkdocs-macros-plugin~=1.0.4 \
    mkdocs-git-revision-date-plugin~=0.3.2 --upgrade
python3 -m mkdocs build -d ../../dist/docs
deactivate