---
nav:
  - index.md
  - "Variables": "variables.md"
  - "Continuous Integration": "ci.md"
  - "Continuous Deployment": "cd.md"
  - "Resources":
    - "Global Resources": "global_resource.md"
  - "CDK Context": "cdk_context.md"
  - "Security": "security.md"
  - "Python Dependencies": "python_dependencies.md"
  - "NPM Dependencies":
    - "Private NPM Registry": "private_npm_registry.md"
  - "GIT Integrations":
    - "CodeCommit": "vcs_codecommit.md"
    - "GitHub": "vcs_github.md"
  - "Networking": "networking.md"