// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// The one file that turns this app into a pipeline. `cdk-cicd deploy-ci` reads it to provision the
// pipeline; `cdk-cicd exec` reads it to inject each stage's config. Nothing else in the app references
// the wrapper. Generated by `cdk-cicd migrate` from the Blueprint sample, then filled in.
import { defineCICD, Repository } from '@cdklabs/cdk-cicd-wrapper';

export default defineCICD({
  application: 'cdk-cicd-wrapper-example',
  repository: Repository.codecommit('cdk-cicd-wrapper-example'),
  // dev auto-approves (inner loop); prod is gated by default. Both single-region here for the sample.
  stages: ['dev', 'prod'],
});
